version: '3.8'
services:

  cocoa-service:
    build:
      context: ./
      target: installer
    command: npm run dev
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/v1/health"]
      interval: 1s
      timeout: 3s
      retries: 10

  test:
    build:
      context: ./
    ports:
      - 8080:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/v1/health"]
      interval: 1s
      timeout: 3s
      retries: 10
      start_period: 3s
