# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ '**' ]
#  pull_request:
#    branches: [ 'main' ]

jobs:

  smoke_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the docker-compose stack
        run: docker-compose up --build -d test
      - name: Wait
        uses: jakejarvis/wait-action@master
        with:
          time: '5s'
      - name: Check running containers
        run: docker ps
      - name: Run smoke test
        run: make smoke

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - run: npm ci
      - run: npm audit
      - run: npm run lint
      - run: npm test
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage/**/*

  build:
    needs: [test, smoke_test]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
#      - name: Install doctl
#        uses: digitalocean/action-doctl@v2
#        with:
#          token: ''
#      - name: Registry login
#        run: doctl registry login
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Docker build
        run: docker build -t cocoa-service:latest -f Dockerfile .
      - name: Docker tag
        run: docker tag cocoa-service:latest registry.digitalocean.com/cocoa/cocoa-service:latest
#      - name: Docker push
#        run: docker push registry.digitalocean.com/cocoa/cocoa-service:latest
